export const ADD_LEAD = 'ADD_LEAD';
export const GET_LEADS_REQUEST = 'GET_LEADS_REQUEST';
export const GET_LEADS_SUCCESS = 'GET_LEADS_SUCCESS';
export const DELETE_SINGLE_LEAD = 'DELETE_SINGLE_LEAD';
export const CREATE_MESSAGE="CREATE_MESSAGE";
export const GET_ERRORS="GET_ERRORS";